### ISSUE TITLE
OSQP fork mentioned in README.md is not available

### ISSUE THREAD

**Issue by kkofler** [d3xsystems/d3x-osqp#8]
README.md states:

> 1. Download the OSQP source <em>from the D3X Systems fork.</em>  (Our fork has
>    logging extensions that have not been merged into the OSQP main branch.)
> ```
> git clone --recursive https://github.com/d3xsystems/osqp
> ```

but that link is a 404, the repository does not appear to be available anywhere public.

**Comment by tipplerow** [comment]
The repository should be visible now. Apologies for the oversight.

**Comment by kkofler** [comment]
Yes, it is visible now. Thanks!
